selmag:
  services:
    catalogue:
      uri: http://localhost:8081
#      username: catalogue_service_user
#      password: password
      registration-id: keycloak
spring:
  datasource:
    url: jdbc:postgresql://localhost:5441/manager
    username: manager
    password: manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
#            provider: keycloak if we have only one registration and provider
            client-id: manager-app
            client-secret: 95R4wm7Wa9jcIDPuR6ED1kggDioWDTZs
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt