server:
  port: 8081

spring:
  security:
    user:
      name: catalogue_service_user
      password: '{noop}password'
      roles: SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5440/catalogue
    username: bxit
    password: aa
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
logging:
  level:
    sql: info
    web: debug