server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/catalogue
    username: bxit
    password: aa
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
  security:
#    user:
#      name: catalogue_service_user
#      password: '{noop}password'
#      roles: SERVICE
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/selmag
logging:
  level:
    sql: info
    web: debug