create schema if not exists user_management;

create table user_management.t_user
(
    id         int primary key generated by default as identity,
    c_username varchar(255) not null unique check ( length(trim(c_username)) > 0 ),
    c_password varchar(60)
);

create table user_management.t_authority
(
    id          int generated by default as identity primary key,
    c_authority varchar not null check ( length(trim(c_authority)) > 0 ) unique
);

create table user_management.t_user_authority
(
    id           int generated by default as identity primary key,
    id_user      int not null references user_management.t_user (id),
    id_authority int not null references user_management.t_authority (id),
    constraint uk_user_authority unique (id_user, id_authority)
)